name: Android Release CI

on:
  push:
    tags:
      - 'v*'   # jalan kalau kamu buat tag, misal: v1.0, v1.1, dst

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload Release APK
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
